name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "LICENSE"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "LICENSE"

jobs:
  ci:
    name: Check linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 12.x
          cache: yarn
          registry-url: "https://registry.npmjs.org/"

      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Run linter
        run: yarn run lint
